import type { Product } from "@/lib/types";

export const BIRD_PRODUCTS: Product[] = [
  {
    id: "b001",
    name: "Wild Bird Premium Seed Mix",
    slug: "wild-bird-premium-seed-mix",
    category: "bird",
    price: 15.99,
    rating: 4.8,
    reviewCount: 203,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&q=80",
      "https://images.unsplash.com/photo-1570018070607-a48f702d74e0?w=600&q=80",
    ],
    tags: ["food", "seed", "mixed", "natural"],
    description: "Nutrient-rich blend of sunflower, safflower, millet, and peanuts. Vitamin-fortified.",
    inStock: true,
    freeShipping: false,
  },
  {
    id: "b002",
    name: "Stainless Steel Bird Cage Large",
    slug: "stainless-steel-bird-cage-large",
    category: "bird",
    price: 189.99,
    originalPrice: 239.99,
    rating: 4.7,
    reviewCount: 312,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&q=80",
      "https://images.unsplash.com/photo-1570018070607-a48f702d74e0?w=600&q=80",
    ],
    badge: "sale",
    tags: ["cage", "stainless", "large", "accessories"],
    description: "32\" x 21\" stainless steel cage with 4 feeder cups, 3 perches, and pull-out tray.",
    inStock: true,
    freeShipping: true,
  },
  {
    id: "b003",
    name: "Colorful Bird Swing & Perch Set",
    slug: "colorful-bird-swing-perch-set",
    category: "bird",
    price: 12.99,
    rating: 4.5,
    reviewCount: 187,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&q=80",
      "https://images.unsplash.com/photo-1570018070607-a48f702d74e0?w=600&q=80",
    ],
    badge: "new",
    tags: ["toys", "swing", "perch", "colorful"],
    description: "5-piece set with wooden swings, ladders, and rope perches. Safe, non-toxic materials.",
    inStock: true,
    freeShipping: false,
  },
  {
    id: "b004",
    name: "Parrot Training Treat Sticks",
    slug: "parrot-training-treat-sticks",
    category: "bird",
    price: 9.99,
    rating: 4.6,
    reviewCount: 98,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&q=80",
      "https://images.unsplash.com/photo-1570018070607-a48f702d74e0?w=600&q=80",
    ],
    tags: ["food", "treats", "training", "parrot"],
    description: "Natural fruit & honey flavored treat sticks. No artificial colors. Great for training.",
    inStock: true,
    freeShipping: false,
  },
];
